# Generated by Django 3.2.6 on 2021-11-12 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssociationData_MODEL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ASS_NameAssociation', models.CharField(db_index=True, help_text='هذا الحقل مخصص لإسم الجمعية', max_length=100, verbose_name='إسم الجمعية')),
                ('ASS_Slug', models.SlugField(unique=True, verbose_name='الإسم التعريفي')),
                ('ASS_AssociationLogo', models.ImageField(db_index=True, default='Default_Image.png', upload_to='AssociationData_Image/', verbose_name='شعار الجمعية')),
                ('ASS_Address', models.CharField(db_index=True, max_length=250, verbose_name='العنوان')),
                ('ASS_Mobile', models.CharField(db_index=True, max_length=10, verbose_name='الجوال')),
                ('ASS_Phone', models.CharField(db_index=True, help_text='ضع مفتاح المدينة قبل الرقم مثال:012', max_length=250, verbose_name='الهاتف')),
                ('ASS_Email', models.EmailField(db_index=True, max_length=250, verbose_name='البريد الألكتروني')),
                ('ASS_BankAccount', models.CharField(db_index=True, help_text='مثال: SA000000', max_length=50, verbose_name='الحساب البنكي - الآيبان')),
            ],
            options={
                'ordering': ['ASS_NameAssociation'],
            },
        ),
    ]
