# Generated by Django 3.2.6 on 2021-11-13 12:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0002_delete_associationdata_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalData_MODEL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PER_Avialable', models.BooleanField(db_index=True, default=True, verbose_name='حالة المشترك_نشط')),
                ('FER_Slug', models.SlugField(blank=True, unique=True, verbose_name='الإسم التعريفي')),
                ('PER_FirstName', models.CharField(db_index=True, max_length=50, verbose_name='الإسم الأول')),
                ('PER_FatherName', models.CharField(db_index=True, max_length=50, verbose_name='إسم الاب')),
                ('PER_GrandFatherName', models.CharField(db_index=True, max_length=50, verbose_name='إسم الجد')),
                ('PER_FamilyName', models.CharField(db_index=True, max_length=50, verbose_name='إسم العائلة')),
                ('PER_ImgePersonal', models.ImageField(db_index=True, default='Default_Image.png', upload_to='PersonalData_Image/', verbose_name='الصورة الشخصية')),
                ('PER_IdNumber', models.CharField(db_index=True, max_length=50, verbose_name='رقم الهوية الشخصية')),
                ('PER_Nationality', models.CharField(choices=[('SA', 'Saudi'), ('BA', 'Bahrain'), ('OM', 'Oman'), ('QA', 'Qatar'), ('KU', 'Kuwait'), ('EM', 'Emirates'), ('YE', 'Yemen')], db_index=True, default='SA', max_length=2, verbose_name='الجنسية')),
                ('PER_Mobile', models.CharField(db_index=True, max_length=10, verbose_name='الجوال')),
                ('PER_SocialStatusMarried', models.BooleanField(db_index=True, default=True, verbose_name='الحالة الإجتماعية - أعزب')),
                ('PER_SocialStatusUnmarried', models.BooleanField(db_index=True, verbose_name='الحالة الإجتماعية -متزوج')),
                ('PER_Date_joined', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاريخ الإنضمام للجمعية')),
                ('PER_Customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='اسم المشترك')),
            ],
        ),
    ]
