# Generated by Django 3.2.6 on 2021-11-19 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20211113_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaldata_model',
            name='PER_SocialStatusUnmarried',
            field=models.BooleanField(blank=True, db_index=True, null=True, verbose_name='الحالة الإجتماعية -متزوج'),
        ),
    ]
