# Generated by Django 3.2.6 on 2021-11-19 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20211119_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialdata_model',
            name='FIN_MethodPaymentCheck',
            field=models.BooleanField(db_index=True, default=False, verbose_name='طريقة سداد قيمة اﻷسهم _ شيك'),
        ),
        migrations.AlterField(
            model_name='financialdata_model',
            name='FIN_MethodPaymentTransfer',
            field=models.BooleanField(db_index=True, default=False, verbose_name='طريقة سداد قيمة اﻷسهم _ حوالة'),
        ),
    ]
