# Generated by Django 3.2.6 on 2021-11-19 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20211119_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialdata_model',
            name='FIN_DateShareReceived',
            field=models.DateField(blank=True, db_index=True, help_text='Required Field', null=True, verbose_name='تاريخ استلام اﻷسهم/المشاركات/المستحقات'),
        ),
        migrations.AlterField(
            model_name='financialdata_model',
            name='FIN_SalaryDisbursementDate',
            field=models.DateField(blank=True, db_index=True, help_text='Required Field', null=True, verbose_name='تاريخ صرف الراتب'),
        ),
    ]
