# Generated by Django 3.2.6 on 2021-11-19 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20211119_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaldata_model',
            name='FER_Slug',
            field=models.SlugField(blank=True, verbose_name='الإسم التعريفي'),
        ),
    ]
