# Generated by Django 3.2.6 on 2021-12-02 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_personaldata_model_fer_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='financialdata_model',
            options={'ordering': ['FIN_User']},
        ),
        migrations.AlterModelOptions(
            name='housingdata_model',
            options={'ordering': ['HOU_User']},
        ),
        migrations.AlterModelOptions(
            name='personaldata_model',
            options={'ordering': ['PER_User']},
        ),
        migrations.RenameField(
            model_name='financialdata_model',
            old_name='FIN_Customer',
            new_name='FIN_User',
        ),
        migrations.RenameField(
            model_name='housingdata_model',
            old_name='HOU_Customer',
            new_name='HOU_User',
        ),
        migrations.RenameField(
            model_name='personaldata_model',
            old_name='PER_Customer',
            new_name='PER_User',
        ),
    ]
