# Generated by Django 3.2.6 on 2021-12-04 20:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0011_auto_20211202_2258'),
    ]

    operations = [
        migrations.CreateModel(
            name='Association_Months_MODEL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AM_MonthNumber', models.CharField(choices=[('00', 'Choose The Month Number'), ('01', '01'), ('02', '02'), ('03', '03'), ('04', '04'), ('05', '05'), ('06', '06'), ('07', '07'), ('08', '08'), ('09', '09'), ('10', '10'), ('11', '11'), ('12', '12')], db_index=True, default='00', max_length=2, verbose_name='رقم الشهر')),
                ('AM_MonthName', models.CharField(choices=[('CMN', 'Choose The Month Name'), ('JAN', 'يناير/January(01)/(05)جمادى الأولى'), ('FEB', 'فبراير/Febraury(02)/(06)جمادى الثاني'), ('MAR', 'مارس/March(03)/(07)رجب'), ('APR', 'أبريل/April(04)/(08)شعبان'), ('MAY', 'مايو/May(05)/(09)رمضان'), ('JUN', 'يونيو/June(06)/(10)شوال'), ('JUL', 'يوليو/July(07)/(11)ذو القعدة'), ('AUG', 'أغسطس/August(08)/(12)ذو الخجة'), ('SEP', 'سبتمبر/Septempber(0)/(01)محرم'), ('OCT', 'أكتوبر/October(10)/(02)صفر'), ('NOV', 'نوفمبر/November(11)/(03)ربيع اﻷول'), ('DEC', 'ديسمبر/December(12)/(04)ربيع الثاني')], db_index=True, default='CMN', max_length=3, verbose_name='إسم الشهر')),
                ('AM_User', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='اسم المشترك')),
            ],
            options={
                'ordering': ['AM_MonthName'],
            },
        ),
    ]
