# Generated by Django 3.2.6 on 2021-12-04 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_association_months_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='association_months_model',
            name='AM_DateShareReceived',
            field=models.DateField(blank=True, db_index=True, help_text='Required Field', null=True, verbose_name='تاريخ استلام اﻷسهم/المشاركات/المستحقات'),
        ),
    ]
