# Generated by Django 3.2.6 on 2021-12-04 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_association_months_model_am_datesharereceived'),
    ]

    operations = [
        migrations.AddField(
            model_name='association_months_model',
            name='AM_Notes',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='الملاحظات'),
        ),
    ]
