# Generated by Django 3.2.6 on 2021-12-05 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_association_months_model_am_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='association_months_model',
            name='AM_DeservedAmount',
            field=models.DecimalField(db_index=True, decimal_places=2, default=50, max_digits=8, verbose_name=' المبلغ المستحق'),
        ),
        migrations.AddField(
            model_name='association_months_model',
            name='AM_NumberShares',
            field=models.IntegerField(db_index=True, default=1, verbose_name='عدد الأسهم'),
        ),
        migrations.AddField(
            model_name='association_months_model',
            name='AM_ShareValue',
            field=models.DecimalField(db_index=True, decimal_places=2, default=50, max_digits=8, verbose_name='قيمة السهم'),
        ),
    ]
