# Generated by Django 3.2.6 on 2021-12-07 19:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0015_auto_20211205_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='association_months_model',
            name='AM_User',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='اسم المشترك'),
        ),
    ]
