# Generated by Django 3.2.6 on 2021-12-18 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_remove_association_months_model_am_monthnumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='Monte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MON_Month', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'month_list',
            },
        ),
        migrations.AlterField(
            model_name='association_months_model',
            name='AM_MonthName',
            field=models.CharField(choices=[('CMN', 'Choose The Month Name'), ('JAN', 'يناير/January(01)/(05)جمادى الأولى'), ('FEB', 'فبراير/Febraury(02)/(06)جمادى الثاني'), ('MAR', 'مارس/March(03)/(07)رجب'), ('APR', 'أبريل/April(04)/(08)شعبان'), ('MAY', 'مايو/May(05)/(09)رمضان'), ('JUN', 'يونيو/June(06)/(10)شوال'), ('JUL', 'يوليو/July(07)/(11)ذو القعدة'), ('AUG', 'أغسطس/August(08)/(12)ذو الخجة'), ('SEP', 'سبتمبر/Septempber(9)/(01)محرم'), ('OCT', 'أكتوبر/October(10)/(02)صفر'), ('NOV', 'نوفمبر/November(11)/(03)ربيع اﻷول'), ('DEC', 'ديسمبر/December(12)/(04)ربيع الثاني')], db_index=True, default='CMN', max_length=3, verbose_name='إسم الشهر'),
        ),
    ]
