# Generated by Django 3.2.6 on 2021-12-18 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_auto_20211218_0607'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Monte',
            new_name='Monthes_List',
        ),
    ]
