# Generated by Django 3.2.6 on 2021-12-18 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_rename_monte_monthes_list'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Monthes_List',
            new_name='Monthes_List_MODEL',
        ),
    ]
