# Generated by Django 3.2.6 on 2021-12-18 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_rename_monthes_list_monthes_list_model'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='monthes_list_model',
            options={'ordering': ['MON_MonthName']},
        ),
        migrations.RemoveField(
            model_name='monthes_list_model',
            name='MON_Month',
        ),
        migrations.AddField(
            model_name='monthes_list_model',
            name='MON_MonthName',
            field=models.CharField(default=1, max_length=30, unique=True),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='monthes_list_model',
            table=None,
        ),
    ]
