# Generated by Django 3.2.6 on 2021-12-20 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_auto_20211218_0655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='association_months_model',
            name='AM_MonthName',
            field=models.CharField(choices=[('CMN', 'Choose The Month Name'), ('JAN', 'يناير-January(01)_جمادى الأولى(5)'), ('FEB', 'فبراير-February(02)_جمادى الثاني(6)'), ('MAR', 'مارس-March(03)_رجب(7)'), ('APR', 'أبريل-April(04)_شعبان(8)'), ('MAY', 'مايو-May(05)_رمضان(9)'), ('JUN', 'يونيو-June(06)_شوال(10)'), ('JUL', 'يوليو-July(07)_ذو القعدة(11)'), ('AUG', 'أغسطس-August(08)_ذو الحجة(12)'), ('SEP', 'سبتمبر-September(09)_محرم(1)'), ('OCT', 'أكتوبر-October(10)_صفر(2)'), ('NOV', 'نوفمبر-November(11)_ربيع الأول(3)'), ('DEC', 'ديسمبر-December(12)_ربيع الثاني(4)')], db_index=True, default='CMN', max_length=3, verbose_name='إسم الشهر'),
        ),
        migrations.AlterField(
            model_name='monthes_list_model',
            name='MON_MonthName',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
