# Generated by Django 3.2.6 on 2021-12-24 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_auto_20211221_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='association_months_model',
            name='AM_MonthName',
            field=models.CharField(choices=[('', 'Choose The Month Name'), ('1-January__Jumada Al-Awwal-(5)', '1-January__Jumada Al-Awwal-(5)'), ('2-February_Jumada Al-Thani-(6)', '2-February_Jumada Al-Thani-(6)'), ('3-March______________Rajab-(7)', '3-March______________Rajab-(7)'), ('4-April_____________Shaban-(8)', '4-April_____________Shaban-(8)'), ('5-May______________Ramadan-(9)', '5-May______________Ramadan-(9)'), ('6-June____________Shawwal-(10)', '6-June____________Shawwal-(10)'), ('7-July_________Dhul-Qadah-(11)', '7-July_________Dhul-Qadah-(11)'), ('8-August______Dhul-Hijjah-(12)', '8-August______Dhul-Hijjah-(12)'), ('9-September_______Muharram-(1)', '9-September_______Muharram-(1)'), ('10-October___________Safar-(2)', '10-October___________Safar-(2)'), ('11-November__Rabi Al-Awwal-(3)', '11-November__Rabi Al-Awwal-(3)'), ('12-December__Rabi Al-Thani-(4)', '12-December__Rabi Al-Thani-(4)')], db_index=True, default='', max_length=50, verbose_name='إسم الشهر'),
        ),
    ]
