# Generated by Django 3.2.6 on 2021-12-25 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_alter_association_months_model_am_monthname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='association_months_model',
            name='AM_MonthName',
            field=models.CharField(choices=[('January', '01-January____Jumada1-05'), ('February', '02-February___Jumada2-06'), ('March', '03-March________Rajab-07'), ('April', '04-April_______Shaban-08'), ('May', '05-May________Ramadan-09'), ('June', '06-June_______Shawwal-10'), ('July', '07-July____Dhul-Qadah-11'), ('August', '08-August_Dhul-Hijjah-12'), ('September', '09-September_Muharram-01'), ('October', '10-October______Safar-02'), ('November', '11-November_____Rabi1-03'), ('December', '12-December_____Rabi2-04')], db_index=True, default='Please Choose ', max_length=50, verbose_name='إسم الشهر'),
        ),
    ]
